### ISSUE TITLE
Make BipBuffer generic

### ISSUE THREAD

**Issue by ferristseng** [utaal/spsc-bip-buffer#3]
Any reason `BipBuffer` can't/shouldn't be generic?

I have a fork that I've been using locally that adds it, and it seems to work fine. Thinking about making a PR for it!

**Comment by utaal** [comment]
Hi @ferristseng! Thanks for your contribution, and sorry this fell off my to-do list. What's your use case for a generic `BipBuffer`? When do you need to reserve contiguous slices of a certain type for communication between threads? Or is your use case a simple `spsc` queue?

**Comment by ferristseng** [comment]
Yeah, I was using this for an audio application where decoded samples (`i16`) were sent to a different thread for playing sounds. I ended up switching to crossbeam, so you can close this, unless someone else might need this implemented.
